
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 158
#define YY_END_OF_BUFFER 159
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[351] =
    {   0,
        0,    0,    0,    0,    0,    0,  119,  119,  102,  102,
      159,  158,   84,   13,  103,  153,   15,    8,   86,    3,
        4,    9,   10,   23,   11,    7,   14,  126,  120,   20,
       21,   16,   22,   17,   19,   85,   85,   85,    1,    2,
       18,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,    5,   24,    6,
       12,  157,  154,  157,  155,  157,  119,  105,  104,  158,
      102,   88,   87,  158,   33,   39,   34,   44,   37,   26,
       40,   27,   41,   25,    0,  138,    0,  139,  140,   38,
      138,  126,    0,    0,  128,  127,    0,  128,  132,  120,

      122,  121,  122,   28,   30,   32,   31,   29,   85,  103,
       86,   85,   85,   46,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   54,   85,   85,   85,   85,   85,   85,
       62,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   45,   35,    0,  156,    0,  155,    0,  119,
      118,  114,  106,  116,  115,  107,  108,  109,  110,  111,
      112,  113,  118,  102,  101,   97,   89,   99,   98,   90,
       91,   92,   93,   94,   95,   96,  101,   36,    0,  141,
        0,  144,  129,  130,    0,    0,  132,  134,  133,  134,
      123,  124,   42,   43,   85,   85,   85,   85,   85,   85,

       85,   85,   85,   85,   85,   85,   85,   85,   85,   60,
       85,   85,   63,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,  116,
      117,   99,  100,  142,  143,  145,  146,  131,    0,  150,
      135,  136,  125,   85,   85,   85,   47,   85,   49,   50,
       85,   85,   85,   85,   56,   57,   85,   85,   61,   85,
       65,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   78,   85,   85,  116,   99,  147,  150,
      150,  151,  152,  137,   81,   85,   85,   48,   51,   85,
       85,   85,   85,   59,   85,   85,   85,   85,   69,   85,

       85,   85,   85,   85,   85,   76,   85,   85,   80,  147,
      147,  148,  149,   85,   85,   85,   85,   55,   58,   64,
       85,   85,   68,   70,   71,   72,   73,   74,   85,   85,
       85,   85,   85,   85,   53,   85,   85,   75,   85,   85,
       82,   85,   52,   66,   67,   77,   79,   85,   83,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   28,   26,   29,   30,
       31,   31,   32,   31,   31,   33,   31,   31,   31,   34,
       31,   31,   31,   31,   35,   31,   31,   36,   31,   31,
       37,   38,   39,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   31,   51,   52,   53,   54,
       55,   56,   31,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[70] =
    {   0,
        1,    2,    1,    3,    1,    1,    1,    4,    1,    1,
        1,    1,    1,    1,    5,    1,    6,    6,    6,    1,
        1,    1,    1,    1,    1,    6,    6,    6,    6,    6,
        7,    7,    8,    7,    8,    7,    1,    2,    1,    1,
        7,    6,    6,    6,    6,    6,    6,    7,    7,    7,
        7,    8,    7,    7,    7,    7,    7,    7,    7,    8,
        7,    7,    7,    7,    7,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[366] =
    {   0,
        0,    0,    0,    0,   68,   71,   72,   75,   76,   89,
      603,  604,  604,  579,  604,  604,  578,   73,  604,  604,
      604,  577,   59,  604,   69,   88,  576,  126,  131,  604,
      604,   72,  575,   75,  604,    0,  104,   48,  604,  604,
      574,   88,  536,  538,   77,   56,   70,   73,  539,   76,
      538,  546,  108,  527,  119,  535,  540,  604,   86,  604,
      604,  604,  604,  125,  119,  584,    0,  604,  604,  188,
        0,  604,  604,  248,  604,  604,  604,  604,  604,  604,
      604,  604,  604,  604,  572,  181,  162,  604,  604,  604,
      241,  221,  178,  201,  149,  604,  571,  152,  261,  297,

      188,  604,  209,  562,  604,  604,  604,  561,    0,  604,
      604,  550,  530,  604,  526,  525,  526,  519,  531,  518,
      533,  520,  526,  512,  513,  510,  510,  513,  510,  507,
        0,   95,  511,  205,  509,   91,  133,  513,  506,  144,
      151,  511,  604,  604,  127,  604,  558,  260,  147,    0,
      604,  604,  151,  199,  604,  604,  604,  604,  604,  604,
      604,  604,    0,    0,  604,  604,  265,  267,  604,  604,
      604,  604,  604,  604,  604,  604,    0,  604,  280,  301,
      305,  321,  197,  604,    0,  291,  326,  208,  604,  220,
      202,  604,  604,  604,    0,  503,  488,  497,  469,  481,

      431,  419,  242,  433,  431,  426,  418,  424,  427,    0,
      413,  417,    0,  418,  415,  405,  403,  405,  407,  412,
      398,  394,  393,  405,  395,  399,  402,  404,  390,  286,
        0,  310,    0,  604,  604,  604,  604,  604,  299,  357,
      257,  604,  604,  388,  383,  389,    0,  385,    0,    0,
      376,  382,  370,  371,    0,    0,  365,  362,    0,  363,
        0,  358,  358,  356,  353,  362,  351,  355,  359,  358,
      356,  343,  345,    0,  333,  342,  604,  604,  377,  381,
      401,  604,  604,  604,    0,  333,  334,    0,    0,  329,
      329,  334,  325,    0,  331,  313,  320,  313,    0,  321,

      318,  320,  304,  313,  312,    0,  302,  302,    0,  408,
      426,  604,  604,  304,  292,  285,  285,    0,    0,    0,
      296,  293,    0,    0,    0,    0,    0,    0,  289,  289,
      277,  247,  266,  243,    0,  218,  187,    0,  189,  183,
        0,  168,    0,    0,    0,    0,    0,  158,    0,  604,
      478,  486,  494,  502,  505,  513,  521,  529,  537,  545,
      549,  551,  202,  182,  136
    } ;

static yyconst flex_int16_t yy_def[366] =
    {   0,
      350,    1,  351,  351,  352,  352,  353,  353,  354,  354,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  355,  355,  355,  350,  350,
      350,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  350,  350,  350,
      350,  350,  350,  356,  350,  350,  357,  350,  350,  358,
      359,  350,  350,  360,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  361,  350,  362,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  355,  350,
      350,  355,  355,  350,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  350,  350,  356,  350,  356,  350,  356,  357,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  363,  359,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  364,  350,  350,  350,
      350,  350,  350,  350,  365,  361,  362,  350,  350,  350,
      350,  350,  350,  350,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  350,
      363,  350,  364,  350,  350,  350,  350,  350,  365,  350,
      350,  350,  350,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  350,  350,  350,  350,
      350,  350,  350,  350,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355,  350,
      350,  350,  350,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,    0,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350
    } ;

static yyconst flex_int16_t yy_nxt[674] =
    {   0,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   29,   30,
       31,   32,   33,   34,   35,   36,   36,   36,   36,   36,
       36,   36,   37,   36,   38,   36,   39,   12,   40,   41,
       42,   43,   44,   45,   46,   47,   48,   49,   36,   50,
       36,   51,   36,   36,   36,   36,   52,   53,   54,   55,
       56,   57,   36,   36,   36,   58,   59,   60,   61,   63,
       80,   64,   63,   68,   64,   69,   68,   72,   69,   77,
      112,   81,   82,   73,   65,   65,   65,   65,   65,   65,
       72,   83,   84,  104,  105,   78,   73,  107,  108,  113,

       66,  123,   85,   66,   86,   86,   86,  110,  143,   70,
      124,  111,   70,   74,  115,  116,   87,   88,  120,  117,
       89,  125,  131,  126,  128,  121,   74,  129,  146,  132,
      146,  122,  127,   87,   88,  148,  148,  148,  219,   89,
       91,  239,   92,   92,   93,   91,  212,  100,  100,  100,
      146,  112,  144,  213,   94,  220,  135,  136,   95,   94,
       96,   97,  147,  101,  147,  102,  137,  230,  230,  138,
      113,   94,  140,  179,  221,  179,   94,   98,  180,  180,
      180,  183,  103,  184,  147,   96,  184,  233,   99,  222,
      102,  152,   91,  225,   93,   93,   93,   86,   86,   86,

      227,  226,  228,  183,  153,  154,   94,  231,  184,   87,
       88,  184,  181,   89,  181,  230,  230,  182,  182,  182,
      191,  349,  192,   94,  348,  155,   87,   88,  347,  156,
      157,  238,   89,  346,  158,   91,  243,   92,   92,   93,
      241,  159,  242,  192,  160,  345,  161,  192,  162,   94,
      163,  166,  215,   95,  242,   96,  238,   86,   86,   86,
      191,  243,  216,  217,  167,  168,   94,  242,  192,   87,
       88,  241,   98,   89,  344,  185,  148,  148,  148,  242,
       96,  232,  232,  232,  232,  169,   87,   88,  343,  170,
      171,  284,   89,  188,  172,  189,  180,  180,  180,  251,

      252,  173,  277,  277,  174,  185,  175,  342,  176,  341,
      177,   91,  190,  100,  100,  100,  284,  180,  180,  180,
      189,  182,  182,  182,  240,   94,  278,  278,  340,  101,
      234,  102,  279,  235,  339,  338,  337,  182,  182,  182,
      185,  336,   94,  335,  334,  333,  240,  234,  103,  332,
      236,  331,  235,  237,  279,  330,  102,  329,  188,  240,
      189,  328,  327,  326,  325,  324,  323,  236,  280,  322,
      280,  321,  237,  281,  281,  281,  320,  190,  319,  318,
      317,  240,  316,  315,  314,  189,  282,  309,  310,  283,
      310,  308,  307,  311,  311,  311,  306,  281,  281,  281,

      305,  304,  303,  282,  302,  301,  312,  300,  283,  313,
      282,  299,  298,  283,  297,  296,  295,  281,  281,  281,
      294,  293,  292,  312,  311,  311,  311,  282,  313,  291,
      282,  290,  283,  283,  289,  288,  287,  312,  286,  285,
      313,  276,  311,  311,  311,  275,  274,  282,  273,  272,
      271,  270,  283,  269,  312,  312,  268,  267,  313,  313,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  255,  312,  254,  253,  250,  249,  313,   12,   12,
       12,   12,   12,   12,   12,   12,   62,   62,   62,   62,
       62,   62,   62,   62,   67,   67,   67,   67,   67,   67,

       67,   67,   71,   71,   71,   71,   71,   71,   71,   71,
      109,  109,  109,  145,  145,  145,  145,  145,  145,  145,
      145,  150,  248,  247,  150,  150,  150,  150,  150,  151,
      151,  151,  151,  151,  151,  151,  151,  164,  246,  164,
      245,  164,  164,  164,  164,  165,  165,  165,  165,  165,
      165,  165,  165,  186,  186,  187,  187,  244,  187,  350,
      229,  224,  223,  218,  214,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,
      196,  195,  195,  194,  193,  185,  178,  149,  142,  141,
      139,  134,  133,  130,  119,  118,  114,  106,   90,   79,

       76,   75,  350,   11,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350
    } ;

static yyconst flex_int16_t yy_chk[674] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
       23,    5,    6,    7,    6,    7,    8,    9,    8,   18,
       38,   23,   25,    9,    5,    5,    5,    6,    6,    6,
       10,   25,   25,   32,   32,   18,   10,   34,   34,   38,

        5,   46,   26,    6,   26,   26,   26,   37,   59,    7,
       46,   37,    8,    9,   42,   42,   26,   26,   45,   42,
       26,   47,   50,   47,   48,   45,   10,   48,   64,   50,
      145,   45,   47,   26,   26,   65,   65,   65,  136,   26,
       28,  365,   28,   28,   28,   29,  132,   29,   29,   29,
      149,   55,   59,  132,   28,  136,   53,   53,   28,   29,
       28,   28,   64,   29,  145,   29,   53,  153,  153,   53,
       55,   28,   55,   87,  137,   87,   29,   28,   87,   87,
       87,   95,   29,   95,  149,   28,   98,  364,   28,  137,
       29,   70,   93,  140,   93,   93,   93,   86,   86,   86,

      141,  140,  141,   98,   70,   70,   93,  363,   95,   86,
       86,   98,   94,   86,   94,  154,  154,   94,   94,   94,
      101,  348,  101,   93,  342,   70,   86,   86,  340,   70,
       70,  183,   86,  339,   70,   92,  191,   92,   92,   92,
      188,   70,  188,  103,   70,  337,   70,  101,   70,   92,
       70,   74,  134,   92,  190,   92,  183,   91,   91,   91,
      103,  191,  134,  134,   74,   74,   92,  188,  103,   91,
       91,  190,   92,   91,  336,   99,  148,  148,  148,  190,
       92,  167,  167,  168,  168,   74,   91,   91,  334,   74,
       74,  241,   91,   99,   74,   99,  179,  179,  179,  203,

      203,   74,  230,  230,   74,  186,   74,  333,   74,  332,
       74,  100,   99,  100,  100,  100,  241,  180,  180,  180,
       99,  181,  181,  181,  186,  100,  232,  232,  331,  100,
      180,  100,  239,  180,  330,  329,  322,  182,  182,  182,
      187,  321,  100,  317,  316,  315,  186,  180,  100,  314,
      182,  308,  180,  182,  239,  307,  100,  305,  187,  187,
      187,  304,  303,  302,  301,  300,  298,  182,  240,  297,
      240,  296,  182,  240,  240,  240,  295,  187,  293,  292,
      291,  187,  290,  287,  286,  187,  240,  276,  279,  240,
      279,  275,  273,  279,  279,  279,  272,  280,  280,  280,

      271,  270,  269,  240,  268,  267,  279,  266,  240,  279,
      280,  265,  264,  280,  263,  262,  260,  281,  281,  281,
      258,  257,  254,  279,  310,  310,  310,  280,  279,  253,
      281,  252,  280,  281,  251,  248,  246,  310,  245,  244,
      310,  229,  311,  311,  311,  228,  227,  281,  226,  225,
      224,  223,  281,  222,  310,  311,  221,  220,  311,  310,
      219,  218,  217,  216,  215,  214,  212,  211,  209,  208,
      207,  206,  311,  205,  204,  202,  201,  311,  351,  351,
      351,  351,  351,  351,  351,  351,  352,  352,  352,  352,
      352,  352,  352,  352,  353,  353,  353,  353,  353,  353,

      353,  353,  354,  354,  354,  354,  354,  354,  354,  354,
      355,  355,  355,  356,  356,  356,  356,  356,  356,  356,
      356,  357,  200,  199,  357,  357,  357,  357,  357,  358,
      358,  358,  358,  358,  358,  358,  358,  359,  198,  359,
      197,  359,  359,  359,  359,  360,  360,  360,  360,  360,
      360,  360,  360,  361,  361,  362,  362,  196,  362,  147,
      142,  139,  138,  135,  133,  130,  129,  128,  127,  126,
      125,  124,  123,  122,  121,  120,  119,  118,  117,  116,
      115,  113,  112,  108,  104,   97,   85,   66,   57,   56,
       54,   52,   51,   49,   44,   43,   41,   33,   27,   22,

       17,   14,   11,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"
#line 3 "lex.l"
// Robert Gruener
// Compilers ECE466
// Lexical Analysis
// lex.l

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "tokens.h"
#include "parser.tab.h"
#include "ast.h"
#include "symbol_table.h"

int line_number;
char filename[256];
char string_buffer[MAX_STRING_LITERAL];
char *string_buf_ptr;




#line 750 "lex.yy.c"

#define INITIAL 0
#define IN_COMMENT 1
#define IN_FILE_DIRECTIVE 2
#define IN_STRING 3
#define IN_CHAR 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 26 "lex.l"


#line 944 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 351 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 604 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 28 "lex.l"
{return '[';} /* Operators and Punctuators */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 29 "lex.l"
{return ']';}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 30 "lex.l"
{return '(';}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 31 "lex.l"
{return ')';}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 32 "lex.l"
{return '{';}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 33 "lex.l"
{return '}';}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 34 "lex.l"
{return '.';}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 35 "lex.l"
{return '&';}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 36 "lex.l"
{return '*';}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 37 "lex.l"
{return '+';}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "lex.l"
{return '-';}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 39 "lex.l"
{return '~';}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 40 "lex.l"
{return '!';}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 41 "lex.l"
{return '/';}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 42 "lex.l"
{return '%';}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 43 "lex.l"
{return '<';}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 44 "lex.l"
{return '>';}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 45 "lex.l"
{return '^';}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 46 "lex.l"
{return '?';}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 47 "lex.l"
{return ':';}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 48 "lex.l"
{return ';';}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 49 "lex.l"
{return '=';}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 50 "lex.l"
{return ',';}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 51 "lex.l"
{return '|';}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 52 "lex.l"
{return INDSEL;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 53 "lex.l"
{return PLUSPLUS;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 54 "lex.l"
{return MINUSMINUS;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 55 "lex.l"
{return SHL;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 56 "lex.l"
{return SHR;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 57 "lex.l"
{return LTEQ;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 58 "lex.l"
{return GTEQ;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 59 "lex.l"
{return EQEQ;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 60 "lex.l"
{return NOTEQ;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 61 "lex.l"
{return LOGAND;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 62 "lex.l"
{return LOGOR;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 63 "lex.l"
{return ELLIPSIS;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 64 "lex.l"
{return TIMESEQ;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 65 "lex.l"
{return DIVEQ;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 66 "lex.l"
{return MODEQ;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 67 "lex.l"
{return PLUSEQ;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 68 "lex.l"
{return MINUSEQ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 69 "lex.l"
{return SHLEQ;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 70 "lex.l"
{return SHREQ;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 71 "lex.l"
{return ANDEQ;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 72 "lex.l"
{return OREQ;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 73 "lex.l"
{return XOREQ;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 74 "lex.l"
{return AUTO;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 75 "lex.l"
{return BREAK;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 76 "lex.l"
{return CASE;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 77 "lex.l"
{return CHAR;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 78 "lex.l"
{return CONST;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 79 "lex.l"
{return CONTINUE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 80 "lex.l"
{return DEFAULT;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 81 "lex.l"
{return DO;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 82 "lex.l"
{return DOUBLE;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 83 "lex.l"
{return ELSE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 84 "lex.l"
{return ENUM;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 85 "lex.l"
{return EXTERN;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 86 "lex.l"
{return FLOAT;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 87 "lex.l"
{return FOR;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 88 "lex.l"
{return GOTO;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 89 "lex.l"
{return IF;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 90 "lex.l"
{return INT;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 91 "lex.l"
{return INLINE;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 92 "lex.l"
{return LONG;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 93 "lex.l"
{return REGISTER;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 94 "lex.l"
{return RESTRICT;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 95 "lex.l"
{return RETURN;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 96 "lex.l"
{return SHORT;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 97 "lex.l"
{return SIGNED;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 98 "lex.l"
{return SIZEOF;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 99 "lex.l"
{return STATIC;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 100 "lex.l"
{return STRUCT;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 101 "lex.l"
{return SWITCH;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 102 "lex.l"
{return TYPEDEF;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 103 "lex.l"
{return UNION;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 104 "lex.l"
{return UNSIGNED;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 105 "lex.l"
{return VOID;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 106 "lex.l"
{return VOLATILE;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 107 "lex.l"
{return WHILE;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 108 "lex.l"
{return _BOOL;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 109 "lex.l"
{return _COMPLEX;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 110 "lex.l"
{return _IMAGINARY;}
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 111 "lex.l"
{line_number++;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 112 "lex.l"
{yylval.yystring = yytext; yylval.yystring_size = strlen(yytext); return check_type();}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 113 "lex.l"
{BEGIN(IN_CHAR); string_buf_ptr = string_buffer;} /* Char Literals */
	YY_BREAK

case 87:
YY_RULE_SETUP
#line 115 "lex.l"
{BEGIN(0); *string_buf_ptr = '\0'; yylval.yychar = string_buffer[0]; return CHARLIT;}
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 116 "lex.l"
{/* error - unterminated string constand */;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 117 "lex.l"
{*string_buf_ptr++='\0';}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 118 "lex.l"
{*string_buf_ptr++='\a';}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 119 "lex.l"
{*string_buf_ptr++='\b';}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 120 "lex.l"
{*string_buf_ptr++='\f';}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 121 "lex.l"
{*string_buf_ptr++='\n';}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 122 "lex.l"
{*string_buf_ptr++='\r';}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 123 "lex.l"
{*string_buf_ptr++='\t';}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 124 "lex.l"
{*string_buf_ptr++='\v';}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 125 "lex.l"
{*string_buf_ptr++='\"';}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 126 "lex.l"
{*string_buf_ptr++='\\';}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 127 "lex.l"
{
        unsigned int result;
        (void) sscanf( yytext+1, "%o", &result);
        if (result > 0xff){
            fprintf(stderr, "%s:%d:Warning:Hex escape sequence %s out of range", filename, line_number, yytext);
            result = '\377';
        }
        *string_buf_ptr++ = result;
    }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 136 "lex.l"
{
        int result;
        (void) sscanf( yytext+2, "%x", &result);
        if (result > 0xff){
            fprintf(stderr, "%s:%d:Warning:Hex escape sequence %s out of range", filename, line_number, yytext);
            result = '\377';
        }
        *string_buf_ptr++ = result;
    }
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 145 "lex.l"
{*string_buf_ptr++ = yytext[1];}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 146 "lex.l"
{
        char *yptr = yytext;
        while (*yptr)
            *string_buf_ptr++ = *yptr++;
    }
	YY_BREAK

case 103:
YY_RULE_SETUP
#line 152 "lex.l"
{string_buf_ptr=string_buffer; BEGIN(IN_STRING);} /* String Literals */
	YY_BREAK

case 104:
YY_RULE_SETUP
#line 154 "lex.l"
{BEGIN(0); *string_buf_ptr = '\0'; yylval.yystring = string_buffer; return STRING;}
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 155 "lex.l"
{/* error - unterminated string constand */;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 156 "lex.l"
{*string_buf_ptr++='\0';}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 157 "lex.l"
{*string_buf_ptr++='\a';}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 158 "lex.l"
{*string_buf_ptr++='\b';}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 159 "lex.l"
{*string_buf_ptr++='\f';}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 160 "lex.l"
{*string_buf_ptr++='\n';}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 161 "lex.l"
{*string_buf_ptr++='\r';}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 162 "lex.l"
{*string_buf_ptr++='\t';}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 163 "lex.l"
{*string_buf_ptr++='\v';}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 164 "lex.l"
{*string_buf_ptr++='\"';}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 165 "lex.l"
{*string_buf_ptr++='\\';}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 166 "lex.l"
{
        int result;
        (void) sscanf( yytext+1, "%o", &result);
        if (result > 0xff){
            fprintf(stderr, "%s:%d:Warning:Octal escape sequence %s out of range\n", filename, line_number, yytext);
            result = '\377';
        }
        *string_buf_ptr++ = result;
    }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 175 "lex.l"
{
        int result;
        (void) sscanf( yytext+2, "%x", &result);
        if (result > 0xff){
            fprintf(stderr, "%s:%d:Warning:Hex escape sequence %s out of range\n", filename, line_number, yytext);
            result = '\377';
        }
        *string_buf_ptr++ = result;
    }
	YY_BREAK
case 118:
/* rule 118 can match eol */
YY_RULE_SETUP
#line 184 "lex.l"
{*string_buf_ptr++ = yytext[1];}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 185 "lex.l"
{
        char *yptr = yytext;
        while (*yptr)
            *string_buf_ptr++ = *yptr++;
    }
	YY_BREAK

case 120:
YY_RULE_SETUP
#line 191 "lex.l"
{ /* DECIMAL INTEGER CONSTANTS */
        yylval.n_size = SIZE_INT;
        yylval.n_signed = SIZE_SIGNED;
        (void) sscanf(yytext, "%llu", &yylval.yyint);
        return NUMBER;
    }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 197 "lex.l"
{
        yylval.n_size = SIZE_INT;
        yylval.n_signed = SIZE_UNSIGNED;
        yytext[yyleng-1] = '\0';
        (void) sscanf(yytext, "%llu", &yylval.yyint);
        return NUMBER;
    }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 204 "lex.l"
{
        yylval.n_size = SIZE_LONG;
        yylval.n_signed = SIZE_SIGNED;
        yytext[yyleng-1] = '\0';
        (void) sscanf(yytext, "%llu", &yylval.yyint);
        return NUMBER;
    }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 211 "lex.l"
{
        yylval.n_size = SIZE_LONGLONG;
        yylval.n_signed = SIZE_SIGNED;
        yytext[yyleng-2] = '\0';
        (void) sscanf(yytext, "%llu", &yylval.yyint);
        return NUMBER;
    }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 218 "lex.l"
{
        yylval.n_size = SIZE_LONG;
        yylval.n_signed = SIZE_UNSIGNED;
        yytext[yyleng-2] = '\0';
        (void) sscanf(yytext, "%llu", &yylval.yyint);
        return NUMBER;
    }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 225 "lex.l"
{
        yylval.n_size = SIZE_LONGLONG;
        yylval.n_signed = SIZE_UNSIGNED;
        yytext[yyleng-3] = '\0';
        (void) sscanf(yytext, "%llu", &yylval.yyint);
        return NUMBER;
    } /* END DECIMAL INTEGER CONSTANTS */
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 232 "lex.l"
{ /* OCTAL INTEGER CONSTANTS */
        yylval.n_size = SIZE_INT;
        yylval.n_signed = SIZE_SIGNED;
        (void) sscanf(yytext, "%llo", &yylval.yyint);
        return NUMBER;
    }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 238 "lex.l"
{
        yylval.n_size = SIZE_INT;
        yylval.n_signed = SIZE_UNSIGNED;
        yytext[yyleng-1] = '\0';
        (void) sscanf(yytext, "%llo", &yylval.yyint);
        return NUMBER;
    }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 245 "lex.l"
{
        yylval.n_size = SIZE_LONG;
        yylval.n_signed = SIZE_SIGNED;
        yytext[yyleng-1] = '\0';
        (void) sscanf(yytext, "%llo", &yylval.yyint);
        return NUMBER;
    }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 252 "lex.l"
{
        yylval.n_size = SIZE_LONGLONG;
        yylval.n_signed = SIZE_SIGNED;
        yytext[yyleng-2] = '\0';
        (void) sscanf(yytext, "%llo", &yylval.yyint);
        return NUMBER;
    }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 259 "lex.l"
{
        yylval.n_size = SIZE_LONG;
        yylval.n_signed = SIZE_UNSIGNED;
        yytext[yyleng-2] = '\0';
        (void) sscanf(yytext, "%llo", &yylval.yyint);
        return NUMBER;
    }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 266 "lex.l"
{
        yylval.n_size = SIZE_LONGLONG;
        yylval.n_signed = SIZE_UNSIGNED;
        yytext[yyleng-3] = '\0';
        (void) sscanf(yytext, "%llo", &yylval.yyint);
        return NUMBER;
    } /* END OCTAL INTEGER CONSTANTS */
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 273 "lex.l"
{ /* HEX INTEGER CONSTANTS */
        yylval.n_size = SIZE_INT;
        yylval.n_signed = SIZE_SIGNED;
        (void) sscanf(yytext, "%llx", &yylval.yyint);
        return NUMBER;
    }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 279 "lex.l"
{
        yylval.n_size = SIZE_INT;
        yylval.n_signed = SIZE_UNSIGNED;
        yytext[yyleng-1] = '\0';
        (void) sscanf(yytext, "%llx", &yylval.yyint);
        return NUMBER;
    }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 286 "lex.l"
{
        yylval.n_size = SIZE_LONG;
        yylval.n_signed = SIZE_SIGNED;
        yytext[yyleng-1] = '\0';
        (void) sscanf(yytext, "%llx", &yylval.yyint);
        return NUMBER;
    }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 293 "lex.l"
{
        yylval.n_size = SIZE_LONGLONG;
        yylval.n_signed = SIZE_SIGNED;
        yytext[yyleng-2] = '\0';
        (void) sscanf(yytext, "%llx", &yylval.yyint);
        return NUMBER;
    }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 300 "lex.l"
{
        yylval.n_size = SIZE_LONG;
        yylval.n_signed = SIZE_UNSIGNED;
        yytext[yyleng-2] = '\0';
        (void) sscanf(yytext, "%llx", &yylval.yyint);
        return NUMBER;
    }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 307 "lex.l"
{
        yylval.n_size = SIZE_LONGLONG;
        yylval.n_signed = SIZE_UNSIGNED;
        yytext[yyleng-3] = '\0';
        (void) sscanf(yytext, "%llx", &yylval.yyint);
        return NUMBER;
    } /* END HEX INTEGER CONSTANTS */
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 314 "lex.l"
{ /* DECIMAL REAL CONSTANTS */
        yylval.n_size = SIZE_DOUBLE;
        yylval.n_signed = SIZE_SIGNED;
        (void) sscanf(yytext, "%Lg", &yylval.yydouble);
        return NUMBER;
    }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 320 "lex.l"
{
        yylval.n_size = SIZE_FLOAT;
        yylval.n_signed = SIZE_SIGNED;
        yytext[yyleng-1] = '\0';
        (void) sscanf(yytext, "%Lg", &yylval.yydouble);
        return NUMBER;
    }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 327 "lex.l"
{
        yylval.n_size = SIZE_LONGDOUBLE;
        yylval.n_signed = SIZE_SIGNED;
        yytext[yyleng-1] = '\0';
        (void) sscanf(yytext, "%Lg", &yylval.yydouble);
        return NUMBER;
    }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 334 "lex.l"
{
        yylval.n_size = SIZE_DOUBLE;
        yylval.n_signed = SIZE_SIGNED;
        (void) sscanf(yytext, "%Lg", &yylval.yydouble);
        return NUMBER;
    }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 340 "lex.l"
{
        yylval.n_size = SIZE_FLOAT;
        yylval.n_signed = SIZE_SIGNED;
        yytext[yyleng-1] = '\0';
        (void) sscanf(yytext, "%Lg", &yylval.yydouble);
        return NUMBER;
    }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 347 "lex.l"
{
        yylval.n_size = SIZE_LONGDOUBLE;
        yylval.n_signed = SIZE_SIGNED;
        yytext[yyleng-1] = '\0';
        (void) sscanf(yytext, "%Lg", &yylval.yydouble);
        return NUMBER;
    }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 354 "lex.l"
{
        yylval.n_size = SIZE_DOUBLE;
        yylval.n_signed = SIZE_SIGNED;
        (void) sscanf(yytext, "%Lg", &yylval.yydouble);
        return NUMBER;
    }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 360 "lex.l"
{
        yylval.n_size = SIZE_FLOAT;
        yylval.n_signed = SIZE_SIGNED;
        yytext[yyleng-1] = '\0';
        (void) sscanf(yytext, "%Lg", &yylval.yydouble);
        return NUMBER;
    }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 367 "lex.l"
{
        yylval.n_size = SIZE_LONGDOUBLE;
        yylval.n_signed = SIZE_SIGNED;
        yytext[yyleng-1] = '\0';
        (void) sscanf(yytext, "%Lg", &yylval.yydouble);
        return NUMBER;
    } /* END DECIMAL REAL CONSTANTS */
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 374 "lex.l"
{ /* HEX REAL CONSTANTS */
        yylval.n_size = SIZE_DOUBLE;
        yylval.n_signed = SIZE_SIGNED;
        (void) sscanf(yytext, "%Lg", &yylval.yydouble);
        return NUMBER;
    }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 380 "lex.l"
{
        yylval.n_size = SIZE_FLOAT;
        yylval.n_signed = SIZE_SIGNED;
        yytext[yyleng-1] = '\0';
        (void) sscanf(yytext, "%Lg", &yylval.yydouble);
        return NUMBER;
    }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 387 "lex.l"
{
        yylval.n_size = SIZE_LONGDOUBLE;
        yylval.n_signed = SIZE_SIGNED;
        yytext[yyleng-1] = '\0';
        (void) sscanf(yytext, "%Lg", &yylval.yydouble);
        return NUMBER;
    }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 394 "lex.l"
{
        yylval.n_size = SIZE_DOUBLE;
        yylval.n_signed = SIZE_SIGNED;
        (void) sscanf(yytext, "%Lg", &yylval.yydouble);
        return NUMBER;
    }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 400 "lex.l"
{
        yylval.n_size = SIZE_FLOAT;
        yylval.n_signed = SIZE_SIGNED;
        yytext[yyleng-1] = '\0';
        (void) sscanf(yytext, "%Lg", &yylval.yydouble);
        return NUMBER;
    }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 407 "lex.l"
{
        yylval.n_size = SIZE_LONGDOUBLE;
        yylval.n_signed = SIZE_SIGNED;
        yytext[yyleng-1] = '\0';
        (void) sscanf(yytext, "%Lg", &yylval.yydouble);
        return NUMBER;
    } /* END HEX REAL CONSTANTS */
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 415 "lex.l"
{BEGIN(IN_FILE_DIRECTIVE);} /* Preprocessing Line Number and Filename */
	YY_BREAK

case 154:
/* rule 154 can match eol */
YY_RULE_SETUP
#line 417 "lex.l"
{BEGIN(0);}
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 418 "lex.l"
{line_number=atoi(yytext);}
	YY_BREAK
case 156:
/* rule 156 can match eol */
YY_RULE_SETUP
#line 419 "lex.l"
{strncpy(filename, yytext+1, strlen(yytext)-2);filename[strlen(yytext)-2]='\0';}
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 420 "lex.l"

	YY_BREAK

case 158:
YY_RULE_SETUP
#line 423 "lex.l"
ECHO;
	YY_BREAK
#line 2060 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(IN_COMMENT):
case YY_STATE_EOF(IN_FILE_DIRECTIVE):
case YY_STATE_EOF(IN_STRING):
case YY_STATE_EOF(IN_CHAR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 351 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 351 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 350);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 423 "lex.l"



int check_type(){
    extern struct sym_table *current_scope;
    struct ast_node *cur = get_ident(current_scope, yytext, NAMESPACE_OTHER);
    if (cur != NULL && cur->left != NULL && cur->left->type == AST_TYPEDEF){
        return TYPEDEF_NAME;
    }
    return IDENT;
}

int print_chars(char *str, char *end){
    while (str != end){
        switch (*str){
            case '\0':
                printf("\\0");
                break;
            case '\\':
                printf("\\\\");
                break;
            case '\'':
                printf("\\\'");
                break;
            case '\"':
                printf("\\\"");
                break;
            case '\a':
                printf("\\a");
                break;
            case '\b':
                printf("\\b");
                break;
            case '\f':
                printf("\\f");
                break;
            case '\n':
                printf("\\n");
                break;
            case '\t':
                printf("\\t");
                break;
            case '\r':
                printf("\\r");
                break;
            case '\v':
                printf("\\v");
                break;
            default:
                if (*str > 126 || *str < 32){
                    printf("\\%03o", (unsigned char)*str);
                } else {
                    printf("%c", *str);
                }
                break;
        }
        str++;
    }
    printf("\n");
    return 0;
}

/*main(){*/
	/*line_number = 1;*/
    /*strcpy(filename, "<stdin>");*/
	/*enum tokens tok;*/
    /*const char * number_types[] = {*/
        /*"INT",*/
        /*"LONG",*/
        /*"LONGLONG",*/
        /*"FLOAT",*/
        /*"DOUBLE",*/
        /*"LONGDOUBLE"*/
    /*};*/
    /*const char * token_names[] = {*/
		/*"IDENT",*/
		/*"CHARLIT",*/
		/*"STRING",*/
		/*"NUMBER",*/
		/*"INDSEL",*/
		/*"PLUSPLUS",*/
		/*"MINUSMINUS",*/
		/*"SHL",*/
		/*"SHR",*/
		/*"LTEQ",*/
		/*"GTEQ",*/
		/*"EQEQ",*/
		/*"NOTEQ",*/
		/*"LOGAND",*/
		/*"LOGOR",*/
		/*"ELLIPSIS",*/
		/*"TIMESEQ",*/
		/*"DIVEQ",*/
		/*"MODEQ",*/
		/*"PLUSEQ",*/
		/*"MINUSEQ",*/
		/*"SHLEQ",*/
		/*"SHREQ",*/
		/*"ANDEQ",*/
		/*"OREQ",*/
		/*"XOREQ",*/
		/*"AUTO",*/
		/*"BREAK",*/
		/*"CASE",*/
		/*"CHAR",*/
		/*"CONST",*/
		/*"CONTINUE",*/
		/*"DEFAULT",*/
		/*"DO",*/
		/*"DOUBLE",*/
		/*"ELSE",*/
		/*"ENUM",*/
		/*"EXTERN",*/
		/*"FLOAT",*/
		/*"FOR",*/
		/*"GOTO",*/
		/*"IF",*/
		/*"INLINE",*/
		/*"INT",*/
		/*"LONG",*/
		/*"REGISTER",*/
		/*"RESTRICT",*/
		/*"RETURN",*/
		/*"SHORT",*/
		/*"SIGNED",*/
		/*"SIZEOF",*/
		/*"STATIC",*/
		/*"STRUCT",*/
		/*"SWITCH",*/
		/*"TYPEDEF",*/
		/*"UNION",*/
		/*"UNSIGNED",*/
		/*"VOID",*/
		/*"VOLATILE",*/
		/*"WHILE",*/
		/*"_BOOL",*/
		/*"_COMPLEX",*/
		/*"_IMAGINARY"*/
    /*};*/
	/*while (tok=yylex()){*/
        /*if (tok < 257){*/
            /*printf("%s\t%d\t%c\n", filename, line_number, tok);  */
        /*} */
        /*else {*/
            /*switch(tok){*/
                /*case TOKEOF:*/
                    /*printf("%s\t%d\tTOKEOF\n", filename, line_number);*/
                    /*break;*/
                /*case IDENT:*/
                    /*printf("%s\t%d\tIDENT\t%s\n", filename, line_number, yylval.yystring);*/
                    /*break;*/
                /*case CHARLIT:*/
                    /*printf("%s\t%d\tCHARLIT\t", filename, line_number);*/
                    /*if (string_buf_ptr - string_buffer > 1){*/
                        /*fprintf(stderr, "%s:%d:Warning:Unsupported multibyte character literal truncated to first byte\n", filename, line_number);*/
                    /*}*/
                    /*print_chars(string_buffer, string_buffer+1);*/
                    /*break;*/
                /*case STRING:*/
                    /*printf("%s\t%d\tSTRING\t", filename, line_number);*/
                    /*print_chars(string_buffer, string_buf_ptr);*/
                    /*break;*/
                /*case NUMBER:*/
                    /*printf("%s\t%d\tNUMBER", filename, line_number);*/
                    /*if (yylval.n_size < 3){*/
                        /*printf("\tINTEGER\t%lld\t", yylval.yyint);*/
                    /*} else {*/
                        /*printf("\tREAL\t%Lg\t", yylval.yydouble);*/
                    /*}*/
                    /*if (yylval.n_size < 3 && yylval.n_signed == SIZE_UNSIGNED){*/
                        /*printf("UNSIGNED,");*/
                    /*}*/
                    /*printf("%s\n", number_types[yylval.n_size]);*/
                    /*break;*/
                /*default:*/
                    /*printf("%s\t%d\t%s\n", filename, line_number, token_names[tok-IDENT]);  */
                    /*break;*/
            /*}	*/
        /*}*/
	/*}*/
	/*printf("EOF\n");*/
/*}*/


